Import("env")
env = env.Clone()

# install pre-made graphics
pre = env.Glob("pre/*.pdf")
env.Install(env["BUILD_DIR"], pre)

# set output directory
env.Append(PDFLATEXFLAGS="--output-directory={}".format(env["BUILD_DIR"]))

# compile TeX graphics
texs = env.Glob("tex/*.tex")
pdfs = []

for tex in texs:
  pdfs.append(env.PDF(tex))

Return("pdfs")
